### ISSUE TITLE
first FOR in KurskalAlgorithm functin cuts of last line in input adjacency matrix

### ISSUE THREAD

**Issue by Bloc3k** [AnastasiiaOberemko/IAL#1]
First FOR in KurskalAlgorithm functin cuts of last line in input adjacency matrix, so in won't fill `seznam` propperly.
```
void KruskalAlgorithm () {
	. . .
	for (i = 1; i < pocet-1; i++) {   //<-------------- This FOR ----------- 
		for (j = 0; j < i; j++) {
			//fill in global variable seznam
		}
	}
```

**Comment by Bloc3k** [comment]
I think it's because of  `pocet-1`
So it skips last record, because it is assind as `<` it won't do last index in array.

**Comment by AnastasiiaOberemko** [comment]
Solved. Check if I'm not wrong
